global:
  scrape_interval:     15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
      monitor: 'docker-host-alpha'

rule_files:
  - /etc/prometheus/alert.rules

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'triton-SERVER'
    scrape_interval: 5s
    scrape_tieout: 5s
    honor_timestamps: true
    static_configs:
      - targets: ['localhost:8002']
    metrics_path: /metrics


alerting:
  alertmanagers:
    - static_configs:
      - targets: 
        - 'alertmanager:9093'
      scheme: http
      timeout: 10s
      api_version: v1


#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
